### ISSUE TITLE
Since last update OOM

### ISSUE THREAD

**Issue by pmarmotte2** [ShmuelRonen/ComfyUI-LatentSyncWrapper#111]
# ComfyUI Error Report
## Error Details
- **Node ID:** 210
- **Node Type:** D_LatentSyncNode
- **Exception Type:** torch.cuda.OutOfMemoryError
- **Exception MesIssage:** Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 0 bytes
Requested               : 9.01 GiB
Device limit            : 8.00 GiB
Free (according to CUDA): 6.88 GiB
PyTorch limit (set by user-supplied memory fraction)
                        : 6.40 GiB

Used to work just fine before

**Comment by pmarmotte2** [comment]
Reverting to https://github.com/ShmuelRonen/ComfyUI-LatentSyncWrapper/commit/8f2a008dcb9996b74c5110c009be063e7565c14f
solves the issue

**Comment by mogupta** [comment]
Same issue after the update.

**Comment by mogupta** [comment]
Hi @ShmuelRonen any solution ? checked the most recent update, same issue, I have RTX 3060 12GB VRAM

**Comment by ShmuelRonen** [comment]
The new version (1.5) need more GPU resources then RTX 3060.  It work best on RTX xx90 versions.

**Comment by mogupta** [comment]
I got it to work using 480p video instead of 1080p for less than 15 second audio with the most recent commit. Thanks

**Comment by mogupta** [comment]
@ShmuelRonen one more issue appeared today. Steps to reproduce on RTX 3060 12GB
1. Run flux dev fp8 workflow (Works)
2. run wan21 fp8 workflow  (Works)
3. run latentsync workflow  (Works)
4. Run flux dev fp8 workflow (Fails OOM)
5. run wan21 fp8 workflow (Fails OOM)
6. Restart comfyui container
7. run wan21 fp8 workflow  (Works)
8. run latentsync workflow  (Works)
